name: clusterspark

services:

  sparkmaster:
    image: spark:latest
    command: /opt/spark/sbin/start-master.sh -h 0.0.0.0
    ports:
      - 8181:8080
      - 6066:6066
      - 7077:7077
    environment:
      - SPARK_NO_DAEMONIZE=true